name: diag
on:
  push:
    tags:
      - "*"
  pull_request:
    types: [opened, closed, reopened]

jobs:
  diagnostics:
    name: diagnostics
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"