
#
# based on: https://github.com/marketplace/actions/release-changelog-builder
name: "release"
on:
  release:
    types: [created]

jobs:
  release:
    uses: ./.github/workflows/dotnet.yml
    name: build
    permissions:
      checks: write
    with:
      Directory: ${{ github.workspace }}
      NetCoreVersion: 8.0.100
      Compile:      true
      UnitTests:    true
      Pack:         true
      Push:         true
      NuGetApiUrl:  'https://api.nuget.org/v3/index.json'
    secrets:
      GH_TOKEN:       '${{ github.token }}'
      NUGET_API_KEY:  '${{ secrets.NUGET_API_KEY }}'
    # if: startsWith(github.ref, 'refs/tags/')
    # runs-on: ubuntu-latest
    # steps:
    #   - name: build changelog
    #     id: github_release
    #     uses: mikepenz/release-changelog-builder-action@v3
    #     with:
    #       configuration: "configuration.changelog.json"
    #     env:
    #       GH_TOKEN: ${{ github.token }}
