
#
# based on: https://github.com/marketplace/actions/release-changelog-builder
name: "tag"
on:
  push:
    tags:
    - '**'

jobs:
  tag:
    uses: ./.github/workflows/dotnet.yml
    name: build
    permissions:
      checks: write
    with:
      Directory: ${{ github.workspace }}
      NetCoreVersion: 8.0.100
      Compile:      true
      UnitTests:    true
      Pack:         true
      Push:         true
      NuGetApiUrl:  'https://api.nuget.org/v3/index.json'
    secrets:
      GH_TOKEN:       '${{ github.token }}'
      NUGET_API_KEY:  '${{ secrets.NUGET_API_KEY }}'
